### ISSUE TITLE
Failed to hook GetProAddress  with Win10  X64

### ISSUE THREAD

**Issue by RichardCNN** [jam3sward/quadifier#13] opened 2017-06-26 10:53 UTC
Hi ,James
I released a  X64  verson.But  the process  pushed  out  a messagebox ,
that said "Failed to hook GetProAddress  " .If  ignored , the EXE file also can  launch.
But some shakeed render would  occur. 
I had tested some times, it works well on Win7 .only happen on Win8/Win10!

System:Win10 X64
IDE:VS 2015 
Graphic Card:NV Quadro M4000
Driver of Graphic Card：377.11

**Comment by jam3sward** [comment] 2017-06-29 21:01
I was able to reproduce the same issue here with a Release x64 build on Windows 10 Pro x64, so this is a confirmed bug.... to be investigated.

**Comment by jam3sward** [comment] 2017-06-29 22:12
After some investigation, I found that **GetProcAddress** is returning a valid pointer,
 but **Mhook_SetHook** fails at this line:
[/quadifier/win32/module/source/main.cpp#L556](https://github.com/jam3sward/quadifier/blob/d8bcabdd31fb8fbea1ed5e66f2ce4c38e839379f/quadifier/win32/module/source/main.cpp#L556)

[MHook](http://codefromthe70s.org/mhook24.aspx) is a third-party library, so it's possible there might be an updated version with bug-fixes [here](https://github.com/martona/mhook). Further investigation is needed..

**Comment by jam3sward** [comment] 2017-06-29 22:24
I've just tried the [latest MHook](https://github.com/martona/mhook/commit/e58a58ca31dbe14f202b9b26315bff9f7a32598c) and the issue is still present, so unfortunately I'm not sure how to fix this, without debugging MHook itself.

**Comment by RichardCNN** [comment] 2017-06-30 10:18
Hi,James 
I get it. 
the function name  of "GetProcAddress"   in  kernel32.dll  has changed on win10.
it is still  reserved  in KERNELBASE.dll. so just take replace kernel32.dll with kernelbase.dll. the bug will be solved.

module -> main.cpp  code:
PFNGetProcAddress real_GetProcAddress = reinterpret_cast<PFNGetProcAddress>(
GetProcAddress( GetModuleHandle(L"kernelbase"), "GetProcAddress" ) );

**Comment by jam3sward** [comment] 2017-06-30 11:53
Hi Richard
Thanks, that's interesting! Last night I looked at both the 32-bit and 64-bit versions of kernel32.dll using depends.exe and GetProcAddress appears in both DLLs (with different ordinals, but the same name/decoration). Also, GetProcAddress was returning a valid pointer for kernel32/GetProcAddress, but failing at Mhook_SetHook, so I assumed the problem was there.
I'll take a look at kernelbase and the change as suggested above. Thanks!
James

**Comment by jam3sward** [comment] 2017-06-30 12:59
I've committed an attempted fix for this at c0e81b0, and tested on Windows 10 x64. This hasn't been tested on Windows 7 at time of writing.

**Comment by jam3sward** [comment] 2017-07-03 18:56
I'm closing this as it works for me now.

**Closed as completed by jam3sward** 2017-07-03 18:56 UTC
