### ISSUE TITLE
Fails to start when Graphic quality is “Beautiful” or above

### ISSUE THREAD

**Issue by RichardCNN** [jam3sward/quadifier#12] opened 2017-06-14 09:28 UTC
Hi Jam，
I built the quadifier  with VS 2015.and built a demo in Unity3d 5.3.6f1.it worked well.
 but when i changed the options' value ,it was failed.
1.Needs to have "Show Unity Splash Screen" enabled in Pro"
 you had discussed with Jack. But I met it again and couldn't solve it in your solution.I don't why.
2.it failed  when the option of Graphic quality is  “Beautiful” or above
maybe it  need to be  spported by DX11 or DX12. i see your code has DX11.  

i will appreciate your reply 
thanks 
Richard

intercept.log:

0: DLL_PROCESS_ATTACH
247: CreateWindowExW(?,OleMainThreadWndName,-2147483648,-2147483648 -2147483648x-2147483648)
251: CreateWindowExW(UnityWndClass,,-2147483648,-2147483648 320x240)
254: Direct3DCreate9(32)
254: Settings: passThrough = false
254: Settings: useTexture = false
254: Settings: preventModeChange = true
254: Settings: matchOriginalMSAA = true
254: Settings: stereoIndicator = false
254: Settings: logLevel = info
261: IDirect3D9Proxy(024EFCA0)
303: CreateDevice(0,1,001304E2,70,02255DC4,02255E00)
304: using Direct3D9Ex
1053: CreateWindowExA(?,NVOGLDC invisible,-2147483648,0 -2147483648x0)
1443: IDirect3DDevice9Proxy(0C54C820,02514398)
1443: new IDirect3DDevice9Proxy(0C54C820,02514398)=0C774598
1795: CreateWindowExW(ComboLBox,?,0,24 126x122)
1798: CreateWindowExW(ComboLBox,?,0,24 126x100)
1800: CreateWindowExW(ComboLBox,?,0,24 126x122)
1802: CreateWindowExW(SysHeader32,?,0,0 0x0)
1803: CreateWindowExW(EDIT,,0,0 16384x16384)
1804: CreateWindowExW(tooltips_class32,?,0,0 0x0)
1805: CreateWindowExW(EDIT,,0,0 16384x16384)
1808: CreateWindowExW(CicMarshalWndClass,CicMarshalWnd,0,0 0x0)
1411142: IDirect3DDevice9::Reset: 1920x1080,backBuffers=1,windowed=1
1412177: CreateWindowExW(GLCLASS,,0,0 8x8)
1412181: CreateWindowExA(?,NVOGLDC invisible,-2147483648,0 -2147483648x0)
1412205: CreateWindowExA(?,__wglDummyWindowFodder,-2147483648,-2147483648 -2147483648x0)
1412260: CreateWindowExW(GLCLASS,,0,0 8x8)
1412264: OpenGL forced AA samples = 0
1412264: Create DX render targets
1412267: DX render target surface format: D3DFMT_A8R8G8B8
1412267: DX viewport = 1920x1080
1412267: DX multisample type = D3DMULTISAMPLE_2_SAMPLES
1412267: DX depth/stencil surface format: D3DFMT_D24S8
1412267: error: failed to create DX render target
1412267: starting GL rendering thread
1412267: thread = 8e4
1412267: Error Setting Render Target

**Comment by jam3sward** [comment] 2017-06-14 11:02
If I remember rightly, this is related to the anti-aliasing settings: when you change the graphics quality in Unity, it changes the anti-aliasing level, and Quadifier tries to create a render target with the same anti-aliasing level. At first glance, it looks like that is failing. This used to work quite reliably and I have a feeling something may have changed in the graphics drivers to break it. It may be worth trying to change the matchOriginalMSAA setting in Quadifier's configuration file.

I don't currently have Unity set up to test this, but I'll try and look at this again for you soon.

**Comment by jam3sward** [comment] 2017-06-15 20:33
Just to confirm, I can reproduce this issue on Windows 10 Pro 64-bit with NVIDIA 377.11 drivers: "Fastest", "Fast", "Simple", "Good" all work but "Beautiful" and "Fantastic" fail with "Error Setting Render Target". Suspect this is due to AA (D3DMULTISAMPLE_2_SAMPLES). Will need to investigate further.

**Comment by jam3sward** [comment] 2017-06-15 20:56
This seems to be due to the changes introduced for ATI/AMD support which were merged at 8e31d821e69158f8d45f4b4d65262147f44cd7e9
It seems that passing a share handle to CreateRenderTarget doesn't work when trying to create a multisampled render target on NVIDIA.
I plan to make it detect NVIDIA, and pass NULL on NVIDIA as it used to do in the original version.

**Comment by jam3sward** [comment] 2017-06-15 21:49
I've committed a fix for this issue at d8bcabd.

**Closed as completed by jam3sward** 2017-06-15 21:49 UTC

**Comment by RichardCNN** [comment] 2017-06-17 08:54
Hi, James. Thanks for your fast reply. 
i have tested the fixed version. however  the Graphic driver was crashed.it showed  the opengl driver of the graphic card  take place error.when computer recovered,stereo function don't work anymore.but stereo dectecter is ok.when i changed a new computer ,the stereo function worked well.may be i need to upate and recover the driver of the graphic card. 
I will continus test and learn the quadifier.it is so great! 
Anyway,thanks again.

**Comment by jam3sward** [comment] 2017-06-20 18:24
Hi Richard,
It might be a graphics driver issue, I would try upgrading/reinstalling the graphics drivers in this case. I'm glad you were able to get it working on another PC as it does here. Let me know if you have any other issues.
James
